/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.repaso4;

/**
 *
 * @author Francisco Aranda
 */

public class Interfaz_Principal extends javax.swing.JPanel {
    /**
     * Creates new form Interfaz_Principal
     */
    public Interfaz_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton_Inicio = new javax.swing.JButton();
        jButton_Sistema = new javax.swing.JButton();
        jButton_CuentasUsuario = new javax.swing.JButton();
        jButton_HoraIdioma = new javax.swing.JButton();
        jButton_Updater = new javax.swing.JButton();

        jLabel1.setText("Configuracion PC");

        jButton_Inicio.setText("Inicio");
        jButton_Inicio.addActionListener(this::jButton_InicioActionPerformed);

        jButton_Sistema.setText("Sistema");
        jButton_Sistema.addActionListener(this::jButton_SistemaActionPerformed);

        jButton_CuentasUsuario.setText("Cuentas de Usuario");
        jButton_CuentasUsuario.addActionListener(this::jButton_CuentasUsuarioActionPerformed);

        jButton_HoraIdioma.setText("Hora e Idioma");
        jButton_HoraIdioma.addActionListener(this::jButton_HoraIdiomaActionPerformed);

        jButton_Updater.setText("Windows Update");
        jButton_Updater.addActionListener(this::jButton_UpdaterActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Sistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_CuentasUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_HoraIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Updater, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Inicio)
                .addGap(18, 18, 18)
                .addComponent(jButton_Sistema)
                .addGap(18, 18, 18)
                .addComponent(jButton_CuentasUsuario)
                .addGap(18, 18, 18)
                .addComponent(jButton_HoraIdioma)
                .addGap(18, 18, 18)
                .addComponent(jButton_Updater)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InicioActionPerformed
        java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
        InterfazInicio Ini = new InterfazInicio(parent, true);
        Ini.setVisible(true);
    }//GEN-LAST:event_jButton_InicioActionPerformed

    private void jButton_SistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SistemaActionPerformed
        java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
        InterfazSistema Ini = new InterfazSistema(parent, true);
        Ini.setVisible(true);
    }//GEN-LAST:event_jButton_SistemaActionPerformed

    private void jButton_CuentasUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CuentasUsuarioActionPerformed
        java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
        InterfazCuentas Ini = new InterfazCuentas(parent, true);
        Ini.setVisible(true);
    }//GEN-LAST:event_jButton_CuentasUsuarioActionPerformed

    private void jButton_HoraIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HoraIdiomaActionPerformed
        java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
        InterfazIdiomas Ini = new InterfazIdiomas(parent, true);
        Ini.setVisible(true);
    }//GEN-LAST:event_jButton_HoraIdiomaActionPerformed

    private void jButton_UpdaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdaterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_UpdaterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CuentasUsuario;
    private javax.swing.JButton jButton_HoraIdioma;
    private javax.swing.JButton jButton_Inicio;
    private javax.swing.JButton jButton_Sistema;
    private javax.swing.JButton jButton_Updater;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    void setDefaultCloseOperation(int EXIT_ON_CLOSE) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
